apiVersion: apps/v1
kind: Deployment
metadata:
  name: matilda-frontend
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: matilda-frontend
  template:
    metadata:
      labels:
        app: matilda-frontend
    spec:
      hostNetwork: false
      containers:
      - name: matilda-frontend
        #image: 3.37.191.158:30002/docker-local/matilda-backend:{{.Values.imagetag}}
        image: 15.164.12.54:5000/docker-local/matilda-frontend:{{.Values.imagetag}}
        env:
        - name: KUBECONFIG
          value: "/kube/kube-config"
        ports: []
        resources:
          limits: {}
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: regcred
